version: "3.9"
services:
  web:
    build: ./backend
    env_file:
      - ./backend/.env.example
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    restart: unless-stopped
